### ISSUE TITLE
Micro via support

### ISSUE THREAD

**Issue by jesstedder** [The-Mad-Noodle/Mad-Noodle-Via-Support#4]
I just got my madnoodle micro.  I flashed it with the latest firmware.  When I go to usevia and click authorize device my micro doesn't show up.

**Comment by jessel92** [comment]
@jesstedder, hey! I'm glad it's working now, but that's still a little strange. Did you put it into 3D render mode in the VIA settings?
For some reason, I've found this occasional bug: If it's not in 3D render mode, the keypads won't authorize, and sometimes, the authorize button won't even show up at all. I'm not sure if that's the problem, but if you don't have it currently turned on, you should turn it on, just to be safe, in case you run into this issue again.
